Repository trinodb/trino-go-client, pull requests merged in 2025-04, with the labels that each got.

#137 Add support for optional timeout param in the DSN
  README.md
  trino/trino.go
  trino/trino_test.go
Labels: enhancement, cla-signed

#140 Ensure Query Cancellation on Context Deadline Expiry
  trino/integration_test.go
  trino/trino.go
Labels: bug, cla-signed

#138 Spooling Protocol
  go.mod
  go.sum
  trino/etc/config-pre-466version.properties
  trino/etc/config.properties
  trino/etc/spooling-manager.properties
  trino/integration_test.go
  trino/trino.go
  trino/trino_test.go
Labels: cla-signed
